### ISSUE TITLE
Support lifetime parameters

### ISSUE THREAD

**Issue by sffc** [marcianx/downcast-rs#11]
If I have a trait and a struct with a lifetime parameter, like

```rust
trait MyTrait<'a> {
  fn set_data(&mut self, data: &'a str);
}

struct MyStruct<'a> {
  data: Option<&'s str>,
}

impl<'a> MyTrait<'a> for MyStruct<'a> {
  fn set_data(&mut self, data: &'a str) {
    self.data.replace(data)
  }
}
```

Then I would like if `impl_downcast!(MyTrait<'a>)` would add methods for converting from MyTrait<'a> to MyStruct<'a> with the same lifetime parameter.

I guess [since Any doesn't support non-static lifetimes](https://doc.rust-lang.org/std/any/), this might be hard to implement safely?

**Comment by marcianx** [comment]
Yeah, sorry, `Any` requires `'static`. Support for non-static downcasting [was considered in this RFC](https://github.com/rust-lang/rfcs/blob/master/text/1849-non-static-type-id.md), but then they decided to not go forward with it due to some sharp edges. I'm not aware of a safe abstraction that wouldn't run afoul of the same concerns. Thanks for checking.
