### ISSUE TITLE
Feature Request: Downcast Trait Objects

### ISSUE THREAD

**Issue by asomers** [marcianx/downcast-rs#2]
downcast-rs provides methods to downcast references, but not Trait objects.  Would it be possible to add a method like this to the `downcast` trait?
```rust
fn downcast(self: Box<Self>) -> Box<T> where T: Downcast
```

**Comment by marcianx** [comment]
Sure, I can take a look into adding some such functionality.

**Comment by marcianx** [comment]
@asomers: Could you clarify what precisely you need. I initially thought you probably meant (assuming `Trait: Downcast`) for `impl_downcast!` to produce the following method as well
```
impl Trait {
  fn downcast<T>(self: Box<Self>) -> Result<Box<T>, Box<Self>> {
    ...
  }
}
```
mirroring the one for [`Box<Any>`](https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-2).
Could you confirm that that's what you meant?

I do run into an awkward challenge here in dealing with the conversion for the failure case to reproduce the original `Box<Self>`, and that might sadly require unsafe code -- I have to think more.

Another alternative that I can provide is to add an `into_any` to the `Downcast` trait so that you can easily go from `Box<Self>` to `Box<Any>` so that you can call `Box<Any>`'s `downcast()` method. Of course, then you can't come back to `Box<Self>` safely (i.e. the problem I mentioned above).

Please confirm that I've understood your request correctly and which of these options you would like.

**Comment by asomers** [comment]
Yes, that method is exactly what I would like.

**Comment by marcianx** [comment]
That "awkward challenge" was actually quite easy (I looked at the standard library for how they did it). Just published 1.0.2 with the feature. Cheers!

**Comment by AgarwalPragy** [comment]
I still seem to be getting error with the following code

```rust
let note: Ref<dyn EditableNote> = { ... };
match note.downcast_ref::<dyn Note>() {
  ...
}

```

```rust
error: the `downcast_ref` method cannot be invoked on a trait object
   --> webui/src/agents/notes_manager.rs:299:28
    |
299 |                 match note.downcast_ref::<dyn Note>() {
    |                            ^^^^^^^^^^^^
    | 
   ::: webui/src/editable.rs:20:1
    |
20  | impl_downcast!(EditableNote);
    | ----------------------------- this has a `Sized` requirement

```

Whereas it works fine when downcasting to a concrete struct
```rust
match note.downcast_ref::<MarkdownNote>() {
  ...
}
// works fine
```

I'm on the latest version of downcast-rs
downcast-rs = "1.2.0"

**Comment by marcianx** [comment]
I just split this out in into a separate issue https://github.com/marcianx/downcast-rs/issues/10 since it seems unrelated to the original here, which is support for `Box<dyn Trait>`.
