### ISSUE TITLE
Downcasting std::cell::Ref?

### ISSUE THREAD

**Issue by KeyboardDanni** [marcianx/downcast-rs#8]
Is this something that can be done? I would like to refactor some existing code such that mutable references can be made to multiple entries in a data structure. Currently it is a `HashMap<TypeId, Box<dyn ComponentStoreBase>`, with a function that returns downcast references as `&mut ComponentStore<C>`, where `ComponentStore<C>` implements `ComponentStoreBase`. I would like to turn this into a `HashMap<TypeId, RefCell<Box<dyn ComponentStoreBase>>` and then be able to return references as `RefMut<ComponentStore<C>>`. Unfortunately, I'm not sure where I'd start to implement such a downcast.

Any ideas?

**Comment by marcianx** [comment]
Huh, color me surprised. It _is_ possible due to `RefMut`'s very flexible `.map()`. Unfortunately, since `map()` requires returning a mutable reference, we need an unfortunate `unwrap()` since downcasting returns an `Option`. However, one can check beforehand whether the downcast would succeed.

(In the following code, I removed the `<C>` type argument for simplicity.)
```rust
#[derive(Debug)]
struct ComponentStore(usize);
impl ComponentStoreBase for ComponentStore {}

// Check if a RefCell<Box<dyn ...>> can be downcast.
let component: RefCell<Box<dyn ComponentStoreBase>> =
    RefCell::new(Box::new(ComponentStore(42)));
let is_downcastable = {
    let borrow = component.borrow();
    // Deref past the RefMut and Box.
    let trait_object: &dyn ComponentStoreBase = borrow.deref().deref();
    trait_object.is::<ComponentStore>()
};
println!("is downcastable: {}", is_downcastable);

// Downcast a RefCell<Box<dyn ...>> or panic otherwise.
let downcasted: RefMut<ComponentStore> = RefMut::map(
    component.borrow_mut(),
    // `downcast_mut` auto-derefs past the RefMut and Box.
    |b| b.downcast_mut::<ComponentStore>().unwrap());
println!("{:?}", downcasted);
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=70c9cc256cd0b292cee820b0fbf86f5a). See the code in `main()`. The stuff above it would be generated by `downcast-rs`.

Enjoy!

**Comment by KeyboardDanni** [comment]
Thanks for the response! The downcast works like a charm, but when returning the RefMut from a member function taking a &mut self, the borrow checker still considers the HashMap mutably borrowed, so unless I can convince the compiler otherwise, this has been a bust.

I suppose this isn't quite the right place for borrow checker inquiries though.

**Comment by marcianx** [comment]
Indeed, that is expected for a member function taking `&mut self` and returning a value borrowed from it (i.e. with a derived lifetime). To get the effect you want, the member function would have to take the argument by `&self`. None of the code above requires `RefCell` itself to be borrowed mutably, so that should be possible unless the method needs to do something else mutably with `self`, in which case that mutable functionality might have to be moved out of the method to get the effect you want.
